export const TEXT_RU = {
  account: {
    settingsTitle: "Настройки аккаунта",
    nicknameLabel: "Имя",
    nicknamePlaceholder: "Как к тебе обращаться",
    nicknameSaveButton: "Сохранить",
    nicknameSaving: "Сохраняем...",
    nicknameSaved: "Имя обновлено",
    nicknameError: "Не удалось сохранить имя",
    languageLabel: "Язык приложения",
    genderLabel: "Пол",
    changeGenderButton: "Изменить",
    deleteAccountTitle: "Удалить аккаунт",
    deleteAccountText:
      "Это навсегда удалит вход в аккаунт и личные данные (имя, фото, имя пользователя). Действие необратимо.",
    deleteAccountButton: "Удалить аккаунт",
    deleteAccountConfirmText: "Точно удалить аккаунт? Это нельзя отменить.",
    deleteAccountConfirmButton: "Да, удалить навсегда",
    deleteAccountCancelButton: "Отмена",
    deleteAccountError: "Не удалось удалить аккаунт. Попробуйте ещё раз.",
  },

  dating: {
    introTitle: "Найди пару 💘",
    introSubtitle: "Раздел для тех, кто ещё не в паре. Мы подбираем анкеты не случайно, а по совместимости — на основе тестов и опросов, которые ты уже проходишь в Couple Quizzes.",
    howItWorksTitle: "Как это работает",
    step1Title: "Пройди тесты и опросы",
    step1Text: "Язык любви, доверие и ещё пара тестов — формируют твой профиль",
    step2Title: "Заполни анкету",
    step2Text: "Фото, имя, возраст и немного о себе",
    step3Title: "Смотри подборку",
    step3Text: "Анкеты показываются по убыванию совместимости, не вперемешку",
    step4Title: "Взаимный лайк — переписка",
    step4Text: "Чат открывается прямо в приложении",
    premiumNote: "Бесплатно: 5 анкет в день. Переписка с мэтчем и безлимит — с Premium",
    startButton: "Начать",

    profileTitle: "Твоя анкета",
    photoHint: "Хотя бы одно фото обязательно",
    nameLabel: "Имя",
    namePlaceholder: "Как к тебе обращаться",
    ageLabel: "Возраст",
    agePlaceholder: "18+",
    bioLabel: "О себе",
    bioPlaceholder: "Пара слов о тебе, увлечениях, что важно в отношениях...",
    seekingLabel: "Кого ищешь",
    seekingBoy: "Парня",
    seekingGirl: "Девушку",
    seekingAny: "Не важно",
    personalityTitle: "Психологический профиль",
    personalityHint: "Собран автоматически по твоим результатам тестов — видно всем в анкете",
    personalityEmpty: "Пройди тесты, чтобы здесь появились теги",
    saveButton: "Сохранить анкету",
    savingButton: "Сохраняем...",
    saveError: "Не удалось сохранить анкету. Попробуй ещё раз.",
    photoUploadError: "Не удалось загрузить фото",
    photoUploading: "Загружаем фото...",

    swipeTitle: "Знакомства",
    swipeHint: "Сначала — самые совместимые анкеты",
    compatibilityBadge: "совместимость",
    noCandidatesTitle: "Анкеты закончились",
    noCandidatesText: "Загляни попозже — новые люди появляются постоянно",
    matchAlertText: "Взаимный лайк! Можно писать 🎉",
    loadingCandidates: "Подбираем анкеты...",
    swipesRemainingLabel: "Осталось сегодня: {count}/5",
    dailyLimitTitle: "Бесплатные анкеты на сегодня закончились",
    dailyLimitText: "Возвращайся завтра — лимит обновится. Или оформи Premium и смотри анкеты без ограничений.",
    dailyLimitUnlockButton: "Снять лимит с Premium",

    matchesTitle: "Мэтчи",
    matchesSubtitle: "Взаимные лайки — можно писать первым",
    newMatchLabel: "Новый мэтч 🎉",
    emptyMatchesTitle: "Мэтчей пока нет",
    emptyMatchesText: "Заходи в ленту, чтобы найти первую пару",
    goToSwipeButton: "К анкетам",

    chatPlaceholder: "Сообщение...",
    chatEmpty: "Пока тишина — напиши первым",
    chatLockedTitle: "Переписка — с Premium",
    chatLockedText: "Мэтч уже есть! Чтобы написать первым, нужен Premium — а идеи для сообщения уже готовы ниже.",
    icebreakersTitle: "Идеи для первого сообщения",
    unlockChatButton: "Открыть переписку с Premium",
    blockButton: "Заблокировать",
    reportButton: "Пожаловаться",
    blockConfirmText: "Заблокировать этого человека? Мэтч и переписка исчезнут.",
    reportConfirmText: "Пожаловаться на этого человека? Профиль будет скрыт и от вас, и от него.",
    actionCancelButton: "Отмена",
    blockedSuccess: "Пользователь заблокирован",
    reportedSuccess: "Жалоба отправлена",

    premiumRequiredTitle: "Нужна подписка",
    premiumRequiredText: "Знакомства доступны только с Premium",
  },

  appName: "Couple Quizzes",

  menu: {
  polls: "Опросы",
  games: "Игры",
  tests: "Тесты",
  rewards: "Очки и призы",
  pair: "Пара",
  top: "Топ игроков",
  topPlayers: "Топ игроков",
  profile: "Профиль и статистика",
  pollsAndTests: "Опросы и тесты",
  pollsAndTestsSubtitle: "Узнавайте друг друга через вопросы и весёлые психологические тесты",
  pollsDesc: "Отвечайте на вопросы вместе с партнёром и сравнивайте ответы",
  testsDesc: "Пройдите тест и узнайте что-то новое о себе и своих отношениях",
  pairAndProfile: "Пара и профиль",
  pairAndProfileSubtitle: "Управляйте парой и своими личными настройками",
  pairDesc: "Уровень пары, совместимость и общая статистика",
  profileDesc: "Личная статистика, достижения и настройки аккаунта",
},

  common: {
    back: "Назад",
    start: "Старт",
    next: "Далее",
    finish: "Завершить",
    continue: "Продолжить",
    save: "Сохранить",
    cancel: "Отмена",
    close: "Закрыть",
    claim: "Получить",
    play: "Играть",
    open: "Открыть",
    loading: "Загрузка...",
    noData: "Пока нет данных",
    done: "Готово",
    show: "Показать",
    hide: "Скрыть",
    toMenu: "В меню",
    of: "из",
  },

  home: {
    pairLevel: "Уровень пары",
    toNextLevel: "До следующего уровня",
    noPairGreeting: "Привет, {name}! 👋",
    noPairText: "Создай пару с партнёром, чтобы вместе проходить тесты, опросы и получать бонусы",
    yourPoints: "Ваши очки",
    newbies: "Новички",
    maxLevelReached: "Максимальный уровень",
  },

  welcome: {
    subtitle: "Узнайте друг друга ещё лучше 💞",
    featurePolls: "Парные опросы",
    featureGames: "Игры для двоих",
    featureTop: "Соревнуйтесь в топе",
  },

  aiPsychologist: {
    menuTitle: "AI-психолог для пары",
    menuSubtitle: "Расскажи, что происходит — разберём вместе",
    checkTitle: "Экспресс-чек отношений 🩺",
    checkIntro: "Ответьте на несколько вопросов, и психолог поможет понять, что сейчас происходит в ваших отношениях.",
    questionOfPrefix: "Вопрос",
    questionOfMid: "из",
    yourResult: "Ваш результат",
    whatToDoNow: "Что можно сделать уже сейчас 💞",
    breakdownByTopics: "Разбор по темам 📊",
  },

  bonus: {
    title: "Ежедневный бонус",
    subtitle: "Заходи каждый день и забирай награду",
    day: "День",
    claim: "Получить",
    claimed: "Получено",
    available: "Доступно",
    soon: "Скоро",
    pointsWord: "очков",
  },

  polls: {
    title: "Опросы",
    subtitle: "Узнайте друг друга лучше",
    empty: "Опросы пока недоступны",
    completed: "Пройдено",
    reward: "Награда",
    chooseWhoTakes: "Выберите, кто сейчас проходит опрос.",
  },

  tests: {
    title: "Тесты",
    subtitle: "Проверьте, насколько хорошо вы знаете друг друга",
    empty: "Тесты пока недоступны",
    completed: "Пройдено",
    reward: "Награда",
  },

  games: {
    title: "Игры",
    subtitle: "Играй и зарабатывай очки",
    empty: "Игры пока недоступны",
    completed: "Пройдено",
    reward: "Награда",
    bottle: "Бутылочка",
    whoFirst: "Кто идет первым?",
    spin: "Крутить",
    neverHaveIEver: "Я никогда не...",
    neverHaveIEverDesc:
      "Скажите что-то, чего вы никогда в жизни не делали, и если ваш партнёр делал это, он выполняет задание с карточки.",
    bottleDesc:
      "Крути бутылку и получай романтичные и дерзкие задания для пары.",
    questions90: "90 вопросов",
    questions90Desc:
      "Случайные глубокие вопросы про любовь, чувства и отношения.",
    start: "Начать",
    playAgain: "Сыграть снова",
    nextPage: "Следующая →",
    prevPage: "← Предыдущая",
    finishedTitle: "Игра завершена 🎮",
    completedSuffix: "пройдена.",
    correctAnswersLabel: "Правильных ответов:",
    resultLabel: "Результат:",
    rewardLabel: "Награда:",
    claimPoints: "Забрать очки",
    questionProgress: "Вопрос {current} из {total}",
    nextButton: "Дальше",
    exitGame: "Выйти из игры",
    pointsUnit: "очков",
  },

  rewards: {
    title: "Очки и призы",
    subtitle: "Обменивайте очки на призы",
    wheel: "Колесо призов",
    prizes: "Призы",
    spin: "Крутить колесо",
    notEnoughPoints: "Недостаточно очков",
    yourBalance: "Ваш баланс",

    wheelScreen: {
      spinCostPrefix: "Одно вращение стоит",
      // iOS-вариант этого экрана без визуала колеса (Apple не пропускает
      // simulated gambling с индивидуальных аккаунтов разработчика) —
      // тот же бонус, но подан как открытие подарка, а не как рулетка.
      iosTitle: "Подарки за очки",
      iosCostPrefix: "Одно открытие стоит",
      iosOpenButtonPrefix: "Открыть за",
      iosOpeningLabel: "Открываем...",
      iosFreeSpinsLabel: " · бесплатных открытий:",
      bonusSegmentLabel: "Бонус",
      pointsLabel: "⭐ Очков:",
      todayLabel: "Сегодня:",
      freeSpinsLabel: " · бесплатных прокрутов:",
      spinFailedMessage: "Не удалось прокрутить колесо. Попробуй ещё раз.",
      spinningLabel: "Крутим...",
      spinButtonPrefix: "Крутить за",
      bonusPointsMessage: "Бонус: +{value} очков!",
      bonusSpinMessage:
        "Бонус: +1 бесплатный прокрут! Следующее вращение будет бесплатным и не потратит дневной лимит.",
      prizeWonMessage: "Тебе выпал приз: {title} ({categoryTitle})",
      wonRewardsTitle: "Выпавшие призы",
      emptyPrizesText: "Пока здесь пусто. Заработай очки и крутанни колесо.",
      categoryLabel: "Категория:",
      collapsePrizes: "Свернуть призы",
      showAllPrizes: "Показать все призы",
      congratsTitle: "🎉 Поздравляем!",
      wonPrizeText: "Вы выиграли приз 🎁 Напишите менеджеру, чтобы получить его",
      claimPrizeButton: "Забрать приз 🎁",
      managerMessageTemplate: "Здравствуйте! Я выиграл приз: {title} 🎁",
    },
  },

 pair: {
    leavePairButton: "Расстаться с парой",
    leavePairConfirmText: "Точно расстаться с парой? Это отменит связь с партнёром, но не удалит очки и историю.",
    leavePairConfirmButton: "Да, расстаться",
    leavePairCancelButton: "Отмена",
  title: "Пара",
    historyTitle: "История",
  subtitle: "Ваш прогресс как пары",
  level: "Уровень",
  compatibility: "Совместимость",
  totalPoints: "Всего очков пары",
  nextLevel: "До следующего уровня",
  noPairYet: "Пара еще не подключена",

  // Используются на экране "Пара", когда пары ещё нет / партнёр не
  // подключился (см. PairScreen в app/page.tsx).
  statusNotConnected: "Пара не подключена",
  noPairTitle: "Создай пару",
  noPairText:
    "Пригласи партнёра, чтобы вместе проходить опросы, тесты и игры.",
  invitePartner: "Пригласить партнёра",

  inPair: "Вы в паре",
  you: "Ты",
  partner: "Партнёр",
  currentLevel: "Текущий уровень",
  untilNext: "До следующего",
  dailyQuestion: "Вопрос дня",
  streakInfo: "Серия",
  pairInvite: "Пригласить партнёра",
  pairConnected: "Пара подключена",
  maxLevel: "Макс. уровень",
  levelsMilestonesTitle: "Рубежи уровней",

  dailyQuestionHint: "Отвечайте вместе каждый день и получайте бонусы 💞",
  streakDaysLabel: "Серия",
  streakDaysWord: "дней",
  youAreInPair: "Вы в паре 💕",
  youCreatedPair: "Вы создали пару 💞",
  keepGettingToKnow: "Продолжайте узнавать друг друга 💫",
  sendCodeOrLink:
    "Отправь код или ссылку партнёру, чтобы он подключился к вашей паре.",
  defaultUserName: "Пользователь",
  connectedFallback: "Подключён",
  partnerNotConnectedYet: "Партнёр ещё не подключился",
  partnerNotJoinedYet: "Партнёр ещё не присоединился",
  compatibilityCalculatedPrefix: "Рассчитано по ",
  compatibilityCalculatedMid: " из ",
  compatibilityCalculatedSuffix: " тем",
  takePollsPrompt:
    "Пройдите парные опросы и узнайте, насколько вы подходите друг другу 💞",
  takePollsButton: "Пройти опросы",
  themesCompletedPrefix: "Тем пройдено: ",

  compatibilityInfo: {
    notCalculatedTitle: "Совместимость пока не рассчитана",
    notCalculatedText:
      "Пройдите вместе хотя бы один общий парный опрос — и здесь появится процент совместимости, тип пары и разбор по темам.",
    headerLabel: "Совместимость пары",
    strongSides: "Сильные стороны пары",
    growthZones: "На что стоит обратить внимание",
    byThemes: "Совместимость по темам",
  },

  invite: {
    subtitle:
      "Сначала создай код приглашения, потом отправь ссылку или дай код партнёру.",
    enterCodeAlert: "Введите код приглашения",
    createFirstAlert: "Сначала создай код приглашения",
    linkCopiedAlert: "Ссылка скопирована",
    copyFailedAlert: "Не удалось скопировать ссылку",
    createStepTitle: "1. Создать код приглашения",
    createStepText: "Это создаст твоё приглашение для подключения пары.",
    creating: "Создаём...",
    createCode: "Создать код приглашения",
    linkTitle: "Ссылка-приглашение",
    copy: "Копировать",
    shareLink: "Отправить ссылку",
    joinByCode: "Добавить по коду",
    enterCodeTitle: "Ввести код приглашения",
    enterCodeText: "Если тебе отправили код, введи его здесь.",
    codePlaceholder: "Например: AB12CD",
    joining: "Подключаем...",
    join: "Подключиться",
  },

  streakInfoScreen: {
    title: "Серия пары",
    daysShort: "дн.",
    description:
      "Вы оба отвечаете на вопрос дня подряд и прокачиваете серию пары.",
    nextBonus: "Следующий бонус",
    maxReached: "Максимальный рубеж достигнут 👑",
    milestonesTitle: "Рубежи серии",
    milestonesDesc:
      "Чем длиннее серия, тем больше бонусных очков получает ваша пара.",
    reached: "получено",
    next: "следующий",
    daysInARow: "дней подряд",
    bothAnsweredStreak: "Оба ответили на вопрос дня подряд",
  },
},

  referrals: {
    title: "Пригласить друзей",
    programTitle: "Твоя реферальная программа",
    subtitle:
      "Приглашай друзей в Couple Quizzes и получай +200 очков за каждого нового пользователя, который зашел по твоей ссылке.",
    invitedFriends: "Приглашено друзей",
    earnedPoints: "Заработано очков",
    yourLink: "Твоя ссылка",
    inviteButton: "Пригласить друзей",
    cardText:
      "Получай +200 очков за каждого друга, который откроет приложение по твоей ссылке.",
    linkLoadingFallback: "Ссылка появится после загрузки профиля",
  },

  top: {
    title: "Топ игроков",
    subtitle: "Лучшие пары этого рейтинга",
    place: "Место",
    points: "Очки",
    empty: "Рейтинг пока пуст",
    leaderboard: "Рейтинг",
    leadersOfWeek: "Лидеры недели",
    weeklyReward: "Награда недели",
    topPairsReward: "Пары из топа получают +500 очков",
    weeklyRewardHint:
      "Награда появляется только после завершения недели и только для пар из топ-3 прошлой недели",

    screen: {
      soloSubtitle:
        "Соревнуйся с другими игроками и поднимайся в личном рейтинге.",
      pairSubtitle:
        "Зарабатывайте очки вместе и поднимайте вашу пару в рейтинге.",
      refresh: "Обновить",
      soloTabLabel: "👤 Сольный топ",
      pairTabLabel: "💕 Парный топ",
      currentWeekBadge: "Текущая неделя",
      soloRankingTitle: "👤 Рейтинг игроков",
      pairRankingTitle: "💕 Рейтинг пар",
      soloEmpty:
        "В сольном рейтинге пока никого нет. Пройди первый тест, опрос или игру!",
      pairEmpty:
        "В парном рейтинге пока никого нет. Подключи партнёра и начните зарабатывать очки вместе!",
      youSuffix: " (Вы)",
      leaderOfWeek: "Лидер недели",
      placeTemplate: "Место #{place}",
      collapseRanking: "Свернуть рейтинг",
      showTop10: "Показать топ-10",
      yourPlaceTitle: "👤 Твоё место",
      yourPlaceText:
        "Ты занимаешь {place}-е место и заработал {points} очков за текущую неделю.",
      yourPlaceEmptyText:
        "Ты пока не участвуешь в сольном рейтинге. Заработай первые очки!",
      yourPairPlaceTitle: "💕 Место вашей пары",
      pairNeedsPartnerText:
        "Сначала подключи партнёра, чтобы участвовать в парном рейтинге.",
      yourPairPlaceText:
        "Ваша пара занимает {place}-е место и заработала {points} очков за текущую неделю.",
      pairNoRankYetText:
        "Ваша пара пока не появилась в рейтинге. Заработайте первые совместные очки!",
      weeklyRewardTitle: "🎁 Награда недели",
      soloRewardComingSoon:
        "Награды сольного рейтинга скоро появятся. Сейчас можно соревноваться за место в топе.",
      topThreeRewardPrefix: "Пары, занявшие первые три места, получают",
      connectPartnerForRankingText:
        "Подключите партнёра, чтобы участвовать в парном рейтинге.",
      rewardAlreadyClaimedText: "Награда за прошлую неделю уже получена ✅",
      rewardAvailableText:
        "Ваша пара вошла в топ-3 прошлой недели! Можно забрать награду 🎉",
      rewardOnlyTopThreeText:
        "Награда доступна только парам из топ-3 по итогам прошлой недели.",
      claimRewardButton: "Забрать +500 очков",
    },
  },

  profile: {
    title: "Профиль и статистика",
    name: "Имя",
    username: "Имя пользователя",
    stats: "Статистика",
    pollsCompleted: "Опросов пройдено",
    testsCompleted: "Тестов пройдено",
    gamesPlayed: "Игр сыграно",
    currentBonusDay: "Текущий день бонуса",
    bonusPoints: "Очков из бонусов",
    noPrizes: "Пока призов нет",
    recentPrizes: "Выиграно призов",
    totalPoints: "Всего очков",
  },

  notifications: {
    newLevel: "Новый уровень!",
    rewardReceived: "Награда получена!",
    sectionCompleted: "Раздел пройден!",
    bonusReceived: "Бонус получен!",
    great: "Класс!",
  },

  dailyPairQuestion: {
    title: "Вопрос дня 💞",
    subtitle:
      "Вы оба отвечаете на один и тот же вопрос. Когда ответят оба — можно сравнить результат.",
    pairRequiredAlert: "Сначала нужно подключить пару",
    alreadyAnsweredAlert: "Ты уже ответил(а) на вопрос дня",
    answerLockedAlert: "Ответ на сегодня уже сохранён и его нельзя изменить",
    streakAlert: "🔥 Серия {days} дней!\n+{points} очков",
    matchAlert: "💘 Вы совпали!\n+{points} очков",
    streakAndMatchAlert:
      "🔥 Серия {days} дней!\n+{streakPoints} очков\n💘 Совпадение ответов!\n+{matchPoints} очков",
    answeredWord: "ответил(а)",
    notAnsweredWord: "ещё не ответил(а)",
    sameAnswerHint: "Вы выбрали один и тот же вариант",
    differentAnswerHint: "Ваши ответы отличаются — обсудите это 💬",
    matchedTitle: "💘 Совпадение!",
    differentTitle: "✨ Разные ответы",
    pairPointsSuffix: "очков паре",
    milestoneReached: "Рубеж достигнут!",
    streakDaysInARow: "Вы отвечаете вместе уже {days} дней подряд 💞",
    historyTitle: "История",
    matchedShort: "Совпали 💘",
    differentShort: "Разные ответы ✨",
  },

  paywall: {
    title: "Полный доступ",
    subtitle:
      "Вы прошли все бесплатные опросы. Откройте полный доступ к Couple Quizzes.",
    featurePolls: "🔓 Все опросы",
    featureGames: "🎮 Все игры",
    featureTests: "🧠 Все тесты",
    featureWheel: "🎡 Рулетка призов",
    // iOS-формулировка того же пункта — без слова "рулетка" (см. фикс
    // rewards.wheelScreen.iosTitle для той же причины).
    featureWheelIos: "🎁 Бонусы и подарки",
    featureBonusPoints: "🎁 +500 очков",
    featureDesign: "🎨 Специальный дизайн",
    unlockButton: "Разблокировать Premium",
    choosePaymentSubtitle: "Выбери удобный способ оплаты",
    openingPayment: "Открываем оплату...",
    payWithStars: "⭐ Оплатить через Stars",
    payWithTribute: "💎 Оплатить через Tribute",
    subscribeButton: "Оформить Premium",
    restoreButton: "Восстановить покупки",
    restoringLabel: "Восстанавливаем...",
    subscriptionLength: "Подписка с автопродлением, 1 месяц",
    termsLink: "Условия использования",
    privacyLink: "Политика конфиденциальности",
  },

  completionBonus: {
    prefix: "Ты полностью завершил",
    pollsWord: " опросы",
    testsWord: " тесты",
    sectionWord: " раздел",
    suffix: " и получаешь бонус!",
    pairPointsLabel: "очков пары",
    claimRewardButton: "Забрать награду",
  },

  errors: {
    telegramUserNotConfirmed: "Не удалось подтвердить пользователя Telegram",
    telegramUserNotFound: "Не удалось получить пользователя Telegram",
    telegramNotDetected: "Не удалось определить Telegram",
    saveAnswerFailed: "Не удалось сохранить ответ, попробуй ещё раз",
    pairJoinFailed: "Не удалось подключиться. Проверь код приглашения.",
    pairLeaveFailed: "Не удалось расстаться с парой. Попробуйте ещё раз.",
    pairJoinedSuccess: "Пара успешно подключена 💕",
    pairCreateInviteFailedPrefix: "Не удалось создать приглашение:",
    pairCreateInviteFailed: "Не удалось создать приглашение",
    wheelSpinFailed: "Не удалось прокрутить колесо, попробуй ещё раз",
    wheelInsufficientPoints: "Недостаточно очков для вращения колеса.",
    wheelDailyLimitReached: "Сегодня лимит вращений исчерпан (3 в день).",
    pairRequiredForSpin: "Сначала нужно создать пару",
    bonusAlreadyClaimedToday: "Бонус на сегодня уже забран — приходи завтра 💫",
    bonusClaimFailed: "Не удалось начислить бонус, попробуй ещё раз",
    noActiveSession: "Нет активной сессии, попробуйте войти заново",
    purchaseNotConfirmed: "Не удалось подтвердить покупку",
    noPurchasesToRestore: "Активных покупок не найдено",
    paymentCreateFailed: "Не удалось создать оплату",
    paymentLinkMissing: "Ссылка на оплату не получена",
    telegramInvoiceUnavailable: "Telegram WebApp openInvoice недоступен",
    paymentOpenFailed: "Не удалось открыть оплату",
    linkAppearsAfterProfile: "Ссылка появится после загрузки профиля",
    inviteLinkCopied: "Ссылка приглашения скопирована",
  },

  giveaway: {
    ticketEarned: "🎟️ Вы получили +1 билет за прохождение опроса!",
    totalTicketsLabel: "Всего билетов:",
  },

  genderSelect: {
    title: "Выбери свой пол",
    subtitle:
      "Это нужно только один раз, чтобы показывать тебе подходящие тесты и опросы!",
    boy: "Я парень",
    girl: "Я девушка",
  },

  auth: {
    signInTitle: "Войдите в аккаунт",
    signUpTitle: "Создайте аккаунт",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Пароль",
    submit: "Войти",
    submitSignUp: "Создать аккаунт",
    submitLoading: "Подождите...",
    or: "или",
    appleSignIn: "Войти через Apple ID",
    switchToSignIn: "У меня уже есть аккаунт",
    switchToSignUp: "Создать новый аккаунт",
    checkEmailTitle: "Проверьте почту",
    checkEmailPrefix: "Мы отправили письмо со ссылкой подтверждения на ",
    checkEmailSuffix: ". Перейдите по ней, а затем войдите в аккаунт.",
    gotIt: "Понятно",
    emailPasswordRequired: "Введите email и пароль",
    genericError: "Что-то пошло не так, попробуйте ещё раз",
    appleSignInError: "Не удалось войти через Apple ID, попробуйте ещё раз",
  },
} as const;