export const TEXT_RU = {
 menu: {
  polls: "Опросы",
  games: "Игры",
  tests: "Тесты",
  rewards: "Очки и призы",
  pair: "Пара",
  top: "Топ игроков",
  profile: "Профиль и статистика",
},
  common: {
    back: "Назад",
    start: "Начать",
    continue: "Продолжить",
    claim: "Забрать",
  },
  rewards: {
    title: "Очки и призы",
    spin: "Крутить",
    notEnough: "Недостаточно очков",
  },

  pair: {
  title: "Пара",
  subtitle: "Здесь можно посмотреть статус пары и совместимость.",
  noPairTitle: "Пока вы не в паре",
  noPairText: "Пригласи партнёра по ссылке или подключи его по коду.",
  invitePartner: "Пригласить партнёра",
  dailyQuestion: "Вопрос дня 💞",
  statusNotConnected: "⏳ Статус: пара не подключена",
  statusConnected: "💕 Статус: вы в паре",
  you: "Ты",
  partner: "Партнёр",
  pairLevel: "Уровень пары 💞",
  compatibility: "Совместимость",
  backToPair: "Назад в раздел «Пара»",
  noUsername: "Без username",
  userFallback: "Пользователь",
  maxLevel: "Максимальный уровень",
  untilNext: "До следующего",
},

top: {
  title: "Топ игроков",
  subtitle: "Лучшие пары недели",
  weeklyReward: "Забрать +500 очков",
  noData: "Пока нет данных",
  yourPair: "Ваша пара",
  firstPlace: "1 место",
  secondPlace: "2 место",
  thirdPlace: "3 место",
  weekLeaders: "Лидеры недели",
  back: "Назад",
},
};