export const TEXT_EN = {
  account: {
    settingsTitle: "Account settings",
    nicknameLabel: "Name",
    nicknamePlaceholder: "What should we call you",
    nicknameSaveButton: "Save",
    nicknameSaving: "Saving...",
    nicknameSaved: "Name updated",
    nicknameError: "Couldn't save the name",
    languageLabel: "App language",
    genderLabel: "Gender",
    changeGenderButton: "Change",
    deleteAccountTitle: "Delete account",
    deleteAccountText:
      "This permanently deletes your login and personal data (name, photo, username). This can't be undone.",
    deleteAccountButton: "Delete account",
    deleteAccountConfirmText: "Really delete your account? This can't be undone.",
    deleteAccountConfirmButton: "Yes, delete permanently",
    deleteAccountCancelButton: "Cancel",
    deleteAccountError: "Couldn't delete your account. Please try again.",
  },

  dating: {
    introTitle: "Find a partner 💘",
    introSubtitle: "For people who aren't paired up yet. Profiles aren't matched randomly — they're ranked by compatibility, based on the tests and polls you already take in Couple Quizzes.",
    howItWorksTitle: "How it works",
    step1Title: "Take tests and polls",
    step1Text: "Love language, trust, and a couple more tests build your profile",
    step2Title: "Fill in your profile",
    step2Text: "Photo, name, age, and a bit about you",
    step3Title: "Browse your matches",
    step3Text: "Profiles are shown by compatibility, highest first",
    step4Title: "Mutual like — start chatting",
    step4Text: "Chat opens right inside the app",
    premiumNote: "This section requires Premium",
    startButton: "Get started",

    profileTitle: "Your profile",
    photoHint: "At least one photo is required",
    nameLabel: "Name",
    namePlaceholder: "What should we call you",
    ageLabel: "Age",
    agePlaceholder: "18+",
    bioLabel: "About you",
    bioPlaceholder: "A few words about you, your interests, what matters in a relationship...",
    seekingLabel: "Looking for",
    seekingBoy: "A guy",
    seekingGirl: "A girl",
    seekingAny: "Doesn't matter",
    personalityTitle: "Psychological profile",
    personalityHint: "Built automatically from your test results — visible to everyone on your profile",
    personalityEmpty: "Take tests to see tags appear here",
    saveButton: "Save profile",
    savingButton: "Saving...",
    saveError: "Couldn't save your profile. Please try again.",
    photoUploadError: "Couldn't upload the photo",
    photoUploading: "Uploading photo...",

    swipeTitle: "Dating",
    swipeHint: "Most compatible profiles come first",
    compatibilityBadge: "compatible",
    noCandidatesTitle: "No more profiles",
    noCandidatesText: "Check back later — new people join all the time",
    matchAlertText: "It's a match! You can chat now 🎉",
    loadingCandidates: "Finding profiles...",

    matchesTitle: "Matches",
    matchesSubtitle: "Mutual likes — feel free to message first",
    newMatchLabel: "New match 🎉",
    emptyMatchesTitle: "No matches yet",
    emptyMatchesText: "Head to the feed to find your first match",
    goToSwipeButton: "Browse profiles",

    chatPlaceholder: "Message...",
    chatEmpty: "It's quiet here — say hi first",
    blockButton: "Block",
    reportButton: "Report",
    blockConfirmText: "Block this person? The match and chat will disappear.",
    reportConfirmText: "Report this person? The profile will be hidden from both of you.",
    actionCancelButton: "Cancel",
    blockedSuccess: "User blocked",
    reportedSuccess: "Report sent",

    premiumRequiredTitle: "Premium required",
    premiumRequiredText: "Dating is available with Premium only",
  },

  appName: "Couple Quizzes",

  menu: {
  polls: "Polls",
  games: "Games",
  tests: "Tests",
  rewards: "Points & Rewards",
  pair: "Pair",
  top: "Top Players",
  topPlayers: "Top Players",
  profile: "Profile & Stats",
  pollsAndTests: "Polls and tests",
  pollsAndTestsSubtitle: "Get to know each other through questions and fun psychology tests",
  pollsDesc: "Answer questions together with your partner and compare answers",
  testsDesc: "Take a test and learn something new about yourself and your relationship",
  pairAndProfile: "Pair and profile",
  pairAndProfileSubtitle: "Manage your pair and your personal settings",
  pairDesc: "Pair level, compatibility and shared stats",
  profileDesc: "Personal stats, achievements and account settings",
},

  common: {
    back: "Back",
    start: "Start",
    next: "Next",
    finish: "Finish",
    continue: "Continue",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    claim: "Claim",
    play: "Play",
    open: "Open",
    loading: "Loading...",
    noData: "No data yet",
    done: "Done",
    show: "Show",
    hide: "Hide",
    toMenu: "To menu",
    of: "of",
  },

  home: {
    pairLevel: "Pair level",
    toNextLevel: "To the next level",
    noPairGreeting: "Hi, {name}! 👋",
    noPairText: "Create a pair with your partner to take tests and polls together and earn bonuses",
    yourPoints: "Your points",
    newbies: "Newbies",
    maxLevelReached: "Maximum level",
  },

  welcome: {
    subtitle: "Get to know each other even better 💞",
    featurePolls: "Couple polls",
    featureGames: "Games for two",
    featureTop: "Compete on the leaderboard",
  },

  aiPsychologist: {
    menuTitle: "AI psychologist for couples",
    menuSubtitle: "Tell us what's going on — let's work through it together",
    checkTitle: "Relationship Check-up 🩺",
    checkIntro: "Answer a few questions and the psychologist will help you understand what's going on in your relationship right now.",
    questionOfPrefix: "Question",
    questionOfMid: "of",
    yourResult: "Your result",
    whatToDoNow: "What you can do right now 💞",
    breakdownByTopics: "Breakdown by topic 📊",
  },

  bonus: {
    title: "Daily bonus",
    subtitle: "Come back every day and claim your reward",
    day: "Day",
    claim: "Claim",
    claimed: "Claimed",
    available: "Available",
    soon: "Soon",
    pointsWord: "points",
  },

  polls: {
    title: "Polls",
    subtitle: "Get to know each other better",
    empty: "No polls available yet",
    completed: "Completed",
    reward: "Reward",
    chooseWhoTakes: "Choose who is taking the poll now.",
  },

  tests: {
    title: "Tests",
    subtitle: "See how well you know each other",
    empty: "No tests available yet",
    completed: "Completed",
    reward: "Reward",
  },

  games: {
    title: "Games",
    subtitle: "Play and earn points",
    empty: "No games available yet",
    completed: "Completed",
    reward: "Reward",
    bottle: "Spin the Bottle",
    whoFirst: "Who goes first?",
    spin: "Spin",
    neverHaveIEver: "Never Have I Ever...",
    neverHaveIEverDesc:
      "Say something you have never done in your life. If your partner has done it, they complete a task from the card.",
    bottleDesc:
      "Spin the bottle and get romantic or spicy tasks for couples.",
    questions90: "90 Questions",
    questions90Desc:
      "Random deep questions about love, feelings, and relationships.",
    start: "Start",
    playAgain: "Play again",
    nextPage: "Next →",
    prevPage: "← Previous",
    finishedTitle: "Game finished 🎮",
    completedSuffix: "completed.",
    correctAnswersLabel: "Correct answers:",
    resultLabel: "Result:",
    rewardLabel: "Reward:",
    claimPoints: "Claim points",
    questionProgress: "Question {current} of {total}",
    nextButton: "Next",
    exitGame: "Exit game",
    pointsUnit: "points",
  },

  rewards: {
    title: "Points & Rewards",
    subtitle: "Exchange points for prizes",
    wheel: "Prize Wheel",
    prizes: "Prizes",
    spin: "Spin the wheel",
    notEnoughPoints: "Not enough points",
    yourBalance: "Your balance",

    wheelScreen: {
      spinCostPrefix: "One spin costs",
      iosTitle: "Daily bonus",
      iosCostPrefix: "One reveal costs",
      iosOpenButtonPrefix: "Open for",
      iosOpeningLabel: "Opening...",
      iosFreeSpinsLabel: " · free openings:",
      bonusSegmentLabel: "Bonus",
      pointsLabel: "⭐ Points:",
      todayLabel: "Today:",
      freeSpinsLabel: " · free spins:",
      spinFailedMessage: "Couldn't spin the wheel. Try again.",
      spinningLabel: "Spinning...",
      spinButtonPrefix: "Spin for",
      bonusPointsMessage: "Bonus: +{value} points!",
      bonusSpinMessage:
        "Bonus: +1 free spin! Your next spin will be free and won't use up your daily limit.",
      prizeWonMessage: "You won a prize: {title} ({categoryTitle})",
      wonRewardsTitle: "Prizes won",
      emptyPrizesText: "Nothing here yet. Earn points and spin the wheel.",
      categoryLabel: "Category:",
      collapsePrizes: "Collapse prizes",
      showAllPrizes: "Show all prizes",
      congratsTitle: "🎉 Congratulations!",
      wonPrizeText: "You won a prize 🎁 Message the manager to claim it",
      claimPrizeButton: "Claim prize 🎁",
      managerMessageTemplate: "Hello! I won a prize: {title} 🎁",
    },
  },

 pair: {
    leavePairButton: "Leave pair",
    leavePairConfirmText: "Really leave this pair? This disconnects you from your partner, but doesn't delete points or history.",
    leavePairConfirmButton: "Yes, leave pair",
    leavePairCancelButton: "Cancel",
  title: "Pair",
    historyTitle: "History",
  subtitle: "Your progress as a couple",
  level: "Level",
  compatibility: "Compatibility",
  totalPoints: "Total couple points",
  nextLevel: "To the next level",
  noPairYet: "No pair connected yet",

  // Used on the "Pair" screen when there's no pair yet / the partner
  // hasn't joined (see PairScreen in app/page.tsx).
  statusNotConnected: "Not connected",
  noPairTitle: "Create a pair",
  noPairText:
    "Invite your partner to take polls, tests and games together.",
  invitePartner: "Invite partner",

  inPair: "You are in a pair",
  you: "You",
  partner: "Partner",
  currentLevel: "Current level",
  untilNext: "Until next",
  dailyQuestion: "Question of the Day",
  streakInfo: "Streak",
  pairInvite: "Invite partner",
  pairConnected: "Pair connected",
  maxLevel: "Max level",
  levelsMilestonesTitle: "Level milestones",

  dailyQuestionHint: "Answer together every day and earn bonuses 💞",
  streakDaysLabel: "Streak",
  streakDaysWord: "days",
  youAreInPair: "You are a pair 💕",
  youCreatedPair: "You created a pair 💞",
  keepGettingToKnow: "Keep getting to know each other 💫",
  sendCodeOrLink:
    "Send the code or link to your partner so they can join your pair.",
  defaultUserName: "User",
  connectedFallback: "Connected",
  partnerNotConnectedYet: "Partner hasn't connected yet",
  partnerNotJoinedYet: "Partner hasn't joined yet",
  compatibilityCalculatedPrefix: "Calculated from ",
  compatibilityCalculatedMid: " of ",
  compatibilityCalculatedSuffix: " topics",
  takePollsPrompt:
    "Take polls together and find out how compatible you are 💞",
  takePollsButton: "Take polls",
  themesCompletedPrefix: "Topics completed: ",

  compatibilityInfo: {
    notCalculatedTitle: "Compatibility not calculated yet",
    notCalculatedText:
      "Complete at least one shared poll together and you'll see your compatibility percentage, pair type, and a breakdown by topic here.",
    headerLabel: "Pair compatibility",
    strongSides: "Your pair's strengths",
    growthZones: "What's worth paying attention to",
    byThemes: "Compatibility by topic",
  },

  invite: {
    subtitle:
      "First create an invite code, then send the link or give the code to your partner.",
    enterCodeAlert: "Enter the invite code",
    createFirstAlert: "First create an invite code",
    linkCopiedAlert: "Link copied",
    copyFailedAlert: "Couldn't copy the link",
    createStepTitle: "1. Create an invite code",
    createStepText: "This will create your invite to connect your pair.",
    creating: "Creating...",
    createCode: "Create invite code",
    linkTitle: "Invite link",
    copy: "Copy",
    shareLink: "Send link",
    joinByCode: "Join by code",
    enterCodeTitle: "Enter invite code",
    enterCodeText: "If you were sent a code, enter it here.",
    codePlaceholder: "E.g.: AB12CD",
    joining: "Connecting...",
    join: "Connect",
  },

  streakInfoScreen: {
    title: "Pair streak",
    daysShort: "d",
    description:
      "You're both answering the question of the day back to back and building your pair's streak.",
    nextBonus: "Next bonus",
    maxReached: "Maximum milestone reached 👑",
    milestonesTitle: "Streak milestones",
    milestonesDesc:
      "The longer the streak, the more bonus points your pair earns.",
    reached: "earned",
    next: "next",
    daysInARow: "days in a row",
    bothAnsweredStreak: "You both answered the daily question in a row",
  },
},

  referrals: {
    title: "Invite Friends",
    programTitle: "Your referral program",
    subtitle:
      "Invite friends to Couple Quizzes and get +200 points for each new user who opens the app using your link.",
    invitedFriends: "Friends invited",
    earnedPoints: "Points earned",
    yourLink: "Your link",
    inviteButton: "Invite friends",
    cardText:
      "Get +200 points for each friend who opens the app using your link.",
    linkLoadingFallback: "The link will appear once your profile loads",
  },

  top: {
    title: "Top Players",
    subtitle: "Best couples of this ranking",
    place: "Place",
    points: "Points",
    empty: "The leaderboard is empty for now",
    leaderboard: "Leaderboard",
    leadersOfWeek: "Leaders of the week",
    weeklyReward: "Weekly reward",
    topPairsReward: "Top pairs receive +500 points",
    weeklyRewardHint:
      "The reward appears only after the week ends and only for couples from the previous week's top 3",

    screen: {
      soloSubtitle: "Compete with other players and climb the solo leaderboard.",
      pairSubtitle: "Earn points together and climb the leaderboard as a pair.",
      refresh: "Refresh",
      soloTabLabel: "👤 Solo top",
      pairTabLabel: "💕 Pair top",
      currentWeekBadge: "Current week",
      soloRankingTitle: "👤 Player ranking",
      pairRankingTitle: "💕 Pair ranking",
      soloEmpty:
        "The solo leaderboard is empty for now. Complete your first test, poll, or game!",
      pairEmpty:
        "The pair leaderboard is empty for now. Connect with your partner and start earning points together!",
      youSuffix: " (You)",
      leaderOfWeek: "Leader of the week",
      placeTemplate: "Place #{place}",
      collapseRanking: "Collapse ranking",
      showTop10: "Show top 10",
      yourPlaceTitle: "👤 Your place",
      yourPlaceText: "You're in {place} place and earned {points} points this week.",
      yourPlaceEmptyText: "You're not on the solo leaderboard yet. Earn your first points!",
      yourPairPlaceTitle: "💕 Your pair's place",
      pairNeedsPartnerText:
        "Connect with your partner first to take part in the pair leaderboard.",
      yourPairPlaceText:
        "Your pair is in {place} place and earned {points} points this week.",
      pairNoRankYetText:
        "Your pair hasn't appeared on the leaderboard yet. Earn your first points together!",
      weeklyRewardTitle: "🎁 Weekly reward",
      soloRewardComingSoon:
        "Solo leaderboard rewards are coming soon. For now you can compete for a spot at the top.",
      topThreeRewardPrefix: "Couples who finish in the top three receive",
      connectPartnerForRankingText:
        "Connect with your partner to take part in the pair leaderboard.",
      rewardAlreadyClaimedText: "Last week's reward has already been claimed ✅",
      rewardAvailableText:
        "Your pair made the top 3 last week! You can claim your reward 🎉",
      rewardOnlyTopThreeText:
        "The reward is only available to pairs that finished in the top 3 last week.",
      claimRewardButton: "Claim +500 points",
    },
  },

  profile: {
    title: "Profile & Statistics",
    name: "Name",
    username: "Username",
    stats: "Statistics",
    pollsCompleted: "Polls completed",
    testsCompleted: "Tests completed",
    gamesPlayed: "Games played",
    currentBonusDay: "Current bonus day",
    bonusPoints: "Bonus points",
    noPrizes: "No prizes yet",
    recentPrizes: "Prizes won",
    totalPoints: "Total points",
  },

  notifications: {
    newLevel: "New level!",
    rewardReceived: "Reward received!",
    sectionCompleted: "Section completed!",
    bonusReceived: "Bonus claimed!",
    great: "Nice!",
  },

  dailyPairQuestion: {
    title: "Question of the Day 💞",
    subtitle:
      "You both answer the same question. Once you've both answered, you can compare your results.",
    pairRequiredAlert: "You need to connect with a partner first",
    alreadyAnsweredAlert: "You've already answered today's question",
    answerLockedAlert: "Today's answer is already saved and can't be changed",
    streakAlert: "🔥 {days}-day streak!\n+{points} points",
    matchAlert: "💘 You matched!\n+{points} points",
    streakAndMatchAlert:
      "🔥 {days}-day streak!\n+{streakPoints} points\n💘 Your answers matched!\n+{matchPoints} points",
    answeredWord: "answered",
    notAnsweredWord: "hasn't answered yet",
    sameAnswerHint: "You picked the same option",
    differentAnswerHint: "Your answers are different — talk it through 💬",
    matchedTitle: "💘 It's a match!",
    differentTitle: "✨ Different answers",
    pairPointsSuffix: "points to your pair",
    milestoneReached: "Milestone reached!",
    streakDaysInARow: "You've answered together for {days} days in a row 💞",
    historyTitle: "History",
    matchedShort: "Matched 💘",
    differentShort: "Different answers ✨",
  },

  paywall: {
    title: "Full access",
    subtitle: "You've completed all the free polls. Unlock full access to Couple Quizzes.",
    featurePolls: "🔓 All polls",
    featureGames: "🎮 All games",
    featureTests: "🧠 All tests",
    featureWheel: "🎡 Prize wheel",
    featureBonusPoints: "🎁 +500 points",
    featureDesign: "🎨 Special design",
    unlockButton: "Unlock Premium",
    choosePaymentSubtitle: "Choose a convenient payment method",
    openingPayment: "Opening payment...",
    payWithStars: "⭐ Pay with Stars",
    payWithTribute: "💎 Pay with Tribute",
  },

  completionBonus: {
    prefix: "You've completed all the",
    pollsWord: " polls",
    testsWord: " tests",
    sectionWord: " section",
    suffix: " and earned a bonus!",
    pairPointsLabel: "pair points",
    claimRewardButton: "Claim reward",
  },

  errors: {
    telegramUserNotConfirmed: "Couldn't verify Telegram user",
    telegramUserNotFound: "Couldn't get Telegram user",
    telegramNotDetected: "Couldn't detect Telegram",
    saveAnswerFailed: "Couldn't save your answer, try again",
    pairJoinFailed: "Couldn't connect. Check your invite code.",
    pairLeaveFailed: "Couldn't leave the pair. Please try again.",
    pairJoinedSuccess: "Pair connected successfully 💕",
    pairCreateInviteFailedPrefix: "Couldn't create invite:",
    pairCreateInviteFailed: "Couldn't create invite",
    wheelSpinFailed: "Couldn't spin the wheel, try again",
    wheelInsufficientPoints: "Not enough points to spin the wheel.",
    wheelDailyLimitReached: "Today's spin limit is reached (3 per day).",
    pairRequiredForSpin: "You need to create a pair first",
    bonusAlreadyClaimedToday: "Today's bonus is already claimed — come back tomorrow 💫",
    bonusClaimFailed: "Couldn't add the bonus, try again",
    noActiveSession: "No active session, please sign in again",
    purchaseNotConfirmed: "Couldn't confirm the purchase",
    paymentCreateFailed: "Couldn't create the payment",
    paymentLinkMissing: "Didn't receive a payment link",
    telegramInvoiceUnavailable: "Telegram WebApp openInvoice is unavailable",
    paymentOpenFailed: "Couldn't open the payment",
    linkAppearsAfterProfile: "Your link will appear once your profile loads",
    inviteLinkCopied: "Invite link copied",
  },

  giveaway: {
    ticketEarned: "🎟️ You earned +1 ticket for completing the poll!",
    totalTicketsLabel: "Total tickets:",
  },

  genderSelect: {
    title: "Choose your gender",
    subtitle:
      "You only need this once, so we can show you the right tests and polls!",
    boy: "I'm a guy",
    girl: "I'm a girl",
  },

  auth: {
    signInTitle: "Sign in to your account",
    signUpTitle: "Create an account",
    emailPlaceholder: "Email",
    passwordPlaceholder: "Password",
    submit: "Sign in",
    submitSignUp: "Create account",
    submitLoading: "Please wait...",
    or: "or",
    appleSignIn: "Sign in with Apple ID",
    switchToSignIn: "I already have an account",
    switchToSignUp: "Create a new account",
    checkEmailTitle: "Check your email",
    checkEmailPrefix: "We sent a confirmation link to ",
    checkEmailSuffix: ". Follow the link, then sign in.",
    gotIt: "Got it",
    emailPasswordRequired: "Enter your email and password",
    genericError: "Something went wrong, please try again",
    appleSignInError: "Couldn't sign in with Apple ID, please try again",
  },
} as const;