export const TEXT_EN = {
 menu: {
  polls: "Polls",
  games: "Games",
  tests: "Tests",
  rewards: "Points & Rewards",
  pair: "Pair",
  top: "Top Players",
  profile: "Profile & Stats",
},
common: {
  back: "Back",
  start: "Start",
  next: "Next",
  finish: "Finish",
  continue: "Continue",
  claim: "Claim",
  play: "Play",
  close: "Close",
  loading: "Loading...",
  noData: "No data yet",
},

  pair: {
  title: "Pair",
  subtitle: "Here you can see your pair status and compatibility.",
  noPairTitle: "You are not in a pair yet",
  noPairText: "Invite your partner by link or connect them by code.",
  invitePartner: "Invite Partner",
  dailyQuestion: "Question of the Day 💞",
  statusNotConnected: "⏳ Status: pair not connected",
  statusConnected: "💕 Status: you are in a pair",
  you: "You",
  partner: "Partner",
  pairLevel: "Pair Level 💞",
  compatibility: "Compatibility",
  backToPair: "Back to Pair",
  noUsername: "No username",
  userFallback: "User",
  maxLevel: "Max level",
  untilNext: "Until next",
},

top: {
  title: "Top Players",
  subtitle: "Best pairs of the week",
  weeklyReward: "Claim +500 points",
  noData: "No data yet",
  yourPair: "Your pair",
  firstPlace: "1st place",
  secondPlace: "2nd place",
  thirdPlace: "3rd place",
  weekLeaders: "Weekly leaders",
  back: "Back",
},
};